# -*- coding: utf-8 -*-
"""Task1 _CODSOFT .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12X9HmYpm2BM420Coy4zFV3dRbyu21UaR

IMPORTING IMPORTANT LIBRARIES

TASK-1 : TITANIC SURVIVAL PREDICTION
Batch-Febraury
Domain :Data Sciencc
Aim:To build a model that predicts wheather a passenger on the Titanic survived or not.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""IMPORTING DATASET"""

df = pd.read_csv("/content/Titanic-Dataset .csv")
df.head(10)

df.shape

df.describe()

"""From above cell it is clear that there us missing values in age column"""

df['Survived'].value_counts()

"""Lets visualise the count of survivals wrt pclass ie. passenger class"""

sns.countplot(x=df['Survived'],hue=df['Pclass'])

"""Count of gender"""

df["Sex"]

"""lets visualize the cout of survivals wrt Gender"""

sns.countplot(x=df['Sex'],hue=df['Survived'])

"""Look at survival rate by sex"""

df.groupby('Sex')[['Survived']].mean()

df['Sex'].unique()

"""Transform all male and female in 1 and 0 form"""

from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
df['Sex']=labelencoder.fit_transform(df['Sex'])
df.head()

df['Sex'],df['Survived']

"""Here we see that after convertion the count of male(1 on x axis ) is not survived than that of female(0 on x asix) is Survived"""

sns.countplot(x=df['Sex'],hue=df["Survived"])

df.isna().sum()

"""After dropping non required column"""

df=df.drop(['Age'],axis=1)

"""After droping the value are"""

df_final=df
df_final.head(10)

""" **MODEL TRAINING**"""

X = df[['Pclass','Sex']]
Y= df['Survived']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

from sklearn.linear_model import LogisticRegression
log=LogisticRegression(random_state=0)
log.fit(X_train ,Y_train)

"""**MODEL PREDICTION**"""

pred = print(log.predict(X_test))

print(X_test)

print(Y_test)

"""Here we found that two parmetere are passed in log.predict() function ie.pclass and gender. This show wheather the passenger (based on gender)in passenger class are survived or not"""

import warnings
warnings.filterwarnings("ignore")
res =log.predict([[2,1]])
if(res==0):
  print("Not Survived")
else:
  print("Survived")